@baseUrl = http://localhost:3000/api/v1/tasks

### CREATING THE TASK
POST {{baseUrl}}
Content-Type: application/json

{
    "taskName": "scroll phone",
    "time" : 6,
    "isGood" : true,
    "isCompleted" : false
}

### READING THE TASK
GET {{baseUrl}}

###UPDATING THE TASK
PATCH {{baseUrl}}/678ce6a94f27ebd36712fc2d
### DELETE THE TASK
DELETE {{baseUrl}}/678ce6a94f27ebd36712fc2d